name: decentralize_application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_form_builder: ^9.1.1
  form_field_validator: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  hexcolor: ^3.0.1

dev_dependencies: 
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

get_cli: 
  sub_folder: false

flutter: 
  uses-material-design: true

